version: '3'
services:
  front:
    container_name: front
    build: ./front
    ports:
      - 8080:8080
    volumes:
      - .:/app/
    tty: true
    stdin_open: true
    command: npm run dev
    environment:
      - VUE_APP_URL=0.0.0.0
    networks:
      - proxy

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - proxy

  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/myapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: api
    environment:
      - DB_HOST=db
      - DB=household_development
      - DB_USERNAME=root
      - DB_PASSWORD=root 
      - AUTH0_CLIENT_ID=5DBgj0XDtbpKetjkxFDPN8VE49EnHN3T
      - AUTH0_DOMAIN=household.auth0.com
      - AUTH0_AUDIENCE=http://0.0.0.0:8000
      - AUTH0_MANAGE_AUDIENCE=https://household.auth0.com/api/v2/
      - AUTH0_CONNECTION=household
      - AUTH0_SECRET_KEY=pquh7alwZytMhasiCIl_WnPCfv-Yy1GyCox6o8WCeKSK6xgJu2m96HPdiZFwLuyZ
    links:
      - db
    tty: true
    stdin_open: true
    privileged: true
    networks:
      - proxy
  
networks:
  proxy:
    external: true